apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: 0.0.0.0
  kubeProxyMode: "nftables"
nodes:
  - role: control-plane
    labels:
      ingress-ready: "true"
    extraPortMappings:
      - containerPort: 30080
        hostPort: 80
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 30443
        hostPort: 443
        listenAddress: "0.0.0.0"
        protocol: TCP
