apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: 0.0.0.0
  kubeProxyMode: "nftables"
nodes:
  - role: control-plane
kubeadmConfigPatchesJSON6902:
  - group: kubeadm.k8s.io
    version: v1beta2
    kind: ClusterConfiguration
    patch: |
      - op: add
        path: /apiServer/certSANs/-
        value: host.docker.internal
      - op: add
        path: /apiServer/certSANs/-
        value: 172.24.0.1
