# https://docs.gitlab.com/ee/ci/yaml/includes.html
include:
  - local: .gitlab-ci-template.yml

stages:
  - test
  - build
  - containerize
  - k8s-deploy

test-code:
  stage: test
  extends: .go-test

build-branch:
  stage: build
  extends: .go-build
  except:
    - master

build:
  stage: build
  extends: .go-build
  only:
    - master

pages:
  stage: build
  environment: production
  script:
    - mkdir -p .public/static
    - cp -r ./static/* .public/static
    - cp -r ./templates/* .public
    - rm -rf public
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

release:
  stage: containerize
  extends: .go-release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_REF_NAME =~ /^v\d+\.\d+\.\d+.*$/ || $CI_COMMIT_TAG
      when: manual

containerize:
  stage: containerize
  extends:
    .dockerize
    #  only:
    #    - master

deploy-k8s:
  stage: k8s-deploy
  extends: .k8s-deployment
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
