apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

images:
  - name: dxas90/learn
    newTag: abc1234

commonLabels:
  app: gitops-k8s
  owner: gitops
  env: e2e
generatorOptions:
  annotations:
    note: generated
  disableNameSuffixHash: true
  labels:
    team: DevOps
    type: generated
    env: e2e