name: KinD Deployment
on:
  push:
    branches: [master]
env:
  APP_IMAGE: dxas90/learn
jobs:
  deploy-n-k8s:
    name: "Deploy to KinD"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Kind Cluster
        uses: helm/kind-action@v1.10.0
        with:
          version: v0.29.0
          kubectl_version: v1.30.4
          cluster_name: test-cluster-1
          verbosity: 1
      - name: "Deploy to KinD"
        id: local-path
        run: |
          export LAST_COMMIT_HASH="$${GITHUB_SHA::7}"
          export APP_NAME=learn
          echo "waiting for nodes to be ready ..."
          kubectl wait --for=condition=Ready nodes --all --timeout=5m
          echo "nodes ..."
          kubectl get nodes
          echo "cluster-info ..."
          kubectl cluster-info
          kubectl apply -k k8s
          echo "waiting for pods to be ready ..."
          kubectl wait --for=condition=Ready pods --all --timeout=5m
          kubectl get pods
